version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: wms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - wms-network

volumes:
  mysql_data:
    name: wms-mysql-data

networks:
  wms-network:
    name: wms-network 